name: 'Setup LocalStack'
description: 'Sets up LocalStack in your GitHub Actions workflow.'
author: 'LocalStack Team'

branding:
  icon: 'code'
  color: 'white'

inputs:
  image-tag:
    description: 'LocalStack image tag to use'
    required: true
    default: 'latest'
  use-pro:
    description: 'Whether to use LocalStack Pro (requires a valid API key)'
    required: false
    default: 'false'
  configuration:
    description: 'Configuration variables to use for LocalStack'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - id: setup-localstack
      run: setup-localstack/setup-localstack.sh
      shell: bash
      env:
        IMAGE_TAG: "${{ inputs.image-tag }}"
        USE_PRO: "${{ inputs.use-pro }}"
        CONFIGURATION: "${{ inputs.configuration }}"
