name: Tests for tflocal-validate
on: [ pull_request ]

jobs:
  tflocal-deploy-action-test:
    name: 'Deploys Terraform Files on LocalStack'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup LocalStack
        uses: ./setup-localstack
        with:
          image-tag: 'latest'
          configuration: 'DEBUG=1 DEFAULT_REGION=eu-central-1'
          use-pro: 'true'
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

      - name: Setup terraform and tflocal
        uses: ./setup-local-tools
        with:
          terraform: 'true'
          terraform-version: '0.14.7'
          tflocal: 'true'

      - name: Deploy on LocalStack
        uses: ./tflocal-deploy
        with:
          path: 'etc/terraform'
          github-token: ${{ secrets.GH_TOKEN }}
